name: deploy-book

# Run this when the master or main branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment: main
    
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r Book/requirements.txt

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
    # - name: cache executed notebooks
    #   uses: actions/cache@v3
    #   with:
    #     path: _build/.jupyter_cache
    #     key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}
    #install pdf dependancy
    - name: Install Playwright
      run: |
        pip install playwright
        playwright install

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./Book

    # # Build the book as PDF
    # - name: Build the book as PDF
    #   run: |
    #     jupyter-book build ./Book --builder pdfhtml

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "Book/_build/html"

   

    # Move the PDF to the webpage
    - name: Move PDF to webpage
      run: |
        cp Book/_build/pdf/book.pdf Book/_build/html/book.pdf
  
    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        branch: main
        folder: ./Book/_build/html